# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Directoryui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 329)
        MainWindow.setMinimumSize(QtCore.QSize(491, 329))
        MainWindow.setMaximumSize(QtCore.QSize(491, 329))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonList = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonList.setGeometry(QtCore.QRect(340, 70, 75, 23))
        self.pushButtonList.setObjectName("pushButtonList")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(49, 30, 251, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditDir = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditDir.setObjectName("lineEditDir")
        self.verticalLayout.addWidget(self.lineEditDir)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditFileName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditFileName.setObjectName("lineEditFileName")
        self.verticalLayout.addWidget(self.lineEditFileName)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditLenght = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditLenght.setObjectName("lineEditLenght")
        self.verticalLayout.addWidget(self.lineEditLenght)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(49, 237, 411, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonFirst = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonFirst.setObjectName("pushButtonFirst")
        self.horizontalLayout.addWidget(self.pushButtonFirst)
        self.pushButtonNext = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout.addWidget(self.pushButtonNext)
        self.pushButtonPrev = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonPrev.setObjectName("pushButtonPrev")
        self.horizontalLayout.addWidget(self.pushButtonPrev)
        self.pushButtonLast = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonLast.setObjectName("pushButtonLast")
        self.horizontalLayout.addWidget(self.pushButtonLast)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonList.setText(_translate("MainWindow", "List"))
        self.label.setText(_translate("MainWindow", "Directory"))
        self.label_2.setText(_translate("MainWindow", "File Name"))
        self.label_3.setText(_translate("MainWindow", "Lenght"))
        self.pushButtonFirst.setText(_translate("MainWindow", "First"))
        self.pushButtonNext.setText(_translate("MainWindow", "Move Next"))
        self.pushButtonPrev.setText(_translate("MainWindow", "Move Prev"))
        self.pushButtonLast.setText(_translate("MainWindow", "Last"))
